@extends('../main')
@section('title','Admin')
@section('content')
    @include('../partials/navbar')
    @include('../partials/partials_admin/index')
@endsection
@section('foot')
    @include('../partials/partials_student/foot')
@endsection
